// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAIRFMMBenormX_Own_oNVWxfWCbS4-BBE',
    appId: '1:60677110575:web:c26ee11f12d86e7ada3fda',
    messagingSenderId: '60677110575',
    projectId: 'apotic-4485a',
    authDomain: 'apotic-4485a.firebaseapp.com',
    storageBucket: 'apotic-4485a.firebasestorage.app',
    measurementId: 'G-P06NE92EJ0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9KZsn1Oh-oJr713aS-_CIVyb39mirnJ0',
    appId: '1:60677110575:android:c0043ee21badc20fda3fda',
    messagingSenderId: '60677110575',
    projectId: 'apotic-4485a',
    storageBucket: 'apotic-4485a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBp1rUOQ1FZK1EVmoaHZwMTnu-asZjKUWQ',
    appId: '1:60677110575:ios:1b254c98524bba2fda3fda',
    messagingSenderId: '60677110575',
    projectId: 'apotic-4485a',
    storageBucket: 'apotic-4485a.firebasestorage.app',
    iosClientId: '60677110575-nlgp16310nemsqsdp8m9ig78ab3vuu4m.apps.googleusercontent.com',
    iosBundleId: 'com.example.apotic',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBp1rUOQ1FZK1EVmoaHZwMTnu-asZjKUWQ',
    appId: '1:60677110575:ios:1b254c98524bba2fda3fda',
    messagingSenderId: '60677110575',
    projectId: 'apotic-4485a',
    storageBucket: 'apotic-4485a.firebasestorage.app',
    iosClientId: '60677110575-nlgp16310nemsqsdp8m9ig78ab3vuu4m.apps.googleusercontent.com',
    iosBundleId: 'com.example.apotic',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAIRFMMBenormX_Own_oNVWxfWCbS4-BBE',
    appId: '1:60677110575:web:4b6db1cfafde9db8da3fda',
    messagingSenderId: '60677110575',
    projectId: 'apotic-4485a',
    authDomain: 'apotic-4485a.firebaseapp.com',
    storageBucket: 'apotic-4485a.firebasestorage.app',
    measurementId: 'G-5D18DENLQQ',
  );
}
